using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FloraSoft
{
    public class Pacs008
    {
        public string OutwardID = "";
        public string DetectTime = "";
        public string FrBank = "";
        public string ToBank = ""; 
        public string FrBICFI = "";
        public string ToBICFI = "";
        public string BizMsgIdr = "";
        public string MsgDefIdr = "";
        public string BizSvc = "";
        public string CreDt = "";
        public string MsgId = "";
        public string CreDtTm = "";
        public int NbOfTxs = 0;
        public string InstrId = "";
        public string EndToEndId = "";
        public string TxId = "";
        public int SvcLvlPrtry = 0;
        public string LclInstrmPrtry = "";
        public int CtgyPurpPrtry = 0;
        public string Ccy = "";
        public decimal IntrBkSttlmAmt = 0;
        public string IntrBkSttlmDt = "";
        public string ChrgBr = "";
        public string InstdAgtBICFI = "";
        public string DbtrNm = "";
        public string DbtrAcctId = "";
        public string DbtrAgtBICFI = "";
        public string CdtrAgtBICFI = "";
        public string CdtrNm = "";
        public string CdtrAcctId = "";
        public string FrBranch = "";
        public string ToBranch = "";
        public string FrBranchId = "";
        public string ToBranchId = "";
        public string PmntRsn = "";
        public int    DeptId = 0;
        public string Maker = "";
        public string MakeTime = "";
        public string MakerIP = "";
        public string Checker = "";
        public string CheckTime = "";
        public string CheckerIP = "";
        public string DeletedBy = "";
        public string DeleteTime = "";
        public int StatusID = 0;
    }
    public class Pacs009
    {
        public string OutwardID = "";
        public string FrBank = "";
        public string ToBank = "";
        public string DetectTime = "";
        public string FrBICFI = "";
        public string ToBICFI = "";
        public string BizMsgIdr = "";
        public string MsgDefIdr = "";
        public string BizSvc = "";
        public string CreDt = "";
        public string MsgId = "";
        public string CreDtTm = "";
        public int    NbOfTxs = 0;
        public string SttlmMtd = "";
        public string InstgAgtNm = "";
        public string InstdAgtNm = "";
        public string ClrChanl = "";
        public string LclInstrmPrtry = "";
        public int    SvcLvlPrtry = 0;
        public int    CtgyPurpPrtry = 0;
        public string PmtInstrId = "";
        public string PmtTxId = "";
        public string EndToEndId = "";
        public string IntrBkSttlmCcy = "";
        public decimal IntrBkSttlmAmt = 0;
        public string IntrBkSttlmDt = "";
        public string DbtrBICFI = "";
        public string DbtrAcctId = "";
        public string CdtrBICFI = "";
        public string CdtrAcctId = "";
        public string PmntRsn = "";
        public int DeptId = 0;
        public string Maker = "";
        public string MakeTime = "";
        public string MakerIP = "";
        public string Checker = "";
        public string CheckTime = "";
        public string CheckerIP = "";
        public int    StatusID = 0;
    }
    public class Pacs004
    {
        public string OutwardID = "";
        public string InwardID = "";
        public string DetectTime = "";
        public string FrBICFI = "";
        public string ToBICFI = "";
        public string FrBranchId = "";
        public string BizMsgIdr = "";
        public string MsgDefIdr = "";
        public string BizSvc = "";
        public string CreDt = "";
        public string MsgId = "";
        public string CreDtTm = "";
        public int NbOfTxs = 0;
        public string OrgnlMsgId = "";
        public string OrgnlMsgNmId = "";
        public string OrgnlCreDtTm = "";
        public string RtrRsnPrtry = "";
        public string RtrRsnAddtlInf = "";
        public string RtrId = "";
        public string OrgnlInstrId = "";
        public string OrgnlEndToEndId = "";
        public string OrgnlTxId = "";
        public string RtrdIntrBkSttlmCcy = "";
        public decimal RtrdIntrBkSttlmAmt = 0;
        public string TxInfIntrBkSttlmDt = "";
        public string ChrgBr = "";
        public string InstgAgtBICFI = "";
        public string InstdAgtBICFI = "";
        public decimal TxRefIntrBkSttlmAmt = 0;
        public string TxRefIntrBkSttlmDt = "";
        public int SvcLvlPrtry = 0;
        public string LclInstrmPrtry = "";
        public int CtgyPurpPrtry = 0;
        public string PmtMtd = "";
        public string DbtrNm = "";
        public string DbtrAgtBICFI = "";
        public string CdtrAgtBICFI = "";
        public string CdtrNm = "";
        public string CdtrAcctId = "";
        public int DeptId = 0;
        public string Maker = "";
        public string MakeTime = "";
        public string MakerIP = "";
        public string Checker = "";
        public string CheckTime = "";
        public string CheckerIP = "";
        public string DeletedBy = "";
        public string DeleteTime = "";
        public int StatusID = 0;
    }
}